### ISSUE TITLE
Tag the current state as release.

### ISSUE THREAD

**Issue by MoritzFago** [qpSHiNqp/airport-bssid#1]
Maybe you could tag the current state as release? It is a [requirement](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md) of homebrew to add airport-bssid as a formula.

**Comment by qpSHiNqp** [comment]
OK, I'll tag it soon. Please notice that the program has some trouble when used with El Capitan (pointed out by #3 ). I'm going to look into the issue.

**Comment by qpSHiNqp** [comment]
> @MoritzFago
> Tagged. That works for you? If no problem, please close this issue.

**Comment by MoritzFago** [comment]
thank you.
