### ISSUE TITLE
Does this supported on latest Mac OSX - Sierra

### ISSUE THREAD

**Issue by ppalliyath** [qpSHiNqp/airport-bssid#5]
Hi ,

I would like to know whether this is supported on Sierra Version.

Also please let me know how to use this tool

**Comment by Moorviper** [comment]
https://github.com/qpSHiNqp/airport-bssid/issues/3

**Comment by peteremiljensen** [comment]
I use Sierra and it works perfectly fine

**Comment by mrPsycho** [comment]
same. this tool seems to be very useful!

**Comment by qpSHiNqp** [comment]
I suppose that it is supported on Sierra if we rebulid.
If you have any trouble on newer os version, please report on #7.
