### ISSUE TITLE
It does not work on EI Capitan 10.11.6?

### ISSUE THREAD

**Issue by TsinghuaDatabaseGroup** [qpSHiNqp/airport-bssid#6]
I tried several times. I clams to associate with the bssid. But it did not.

**Comment by FancyQian** [comment]
Yes, my 2.4G and 5G use same ssid, although I specific a bssid, but my OS still associate other one.

**Comment by Moorviper** [comment]
<img width="1524" alt="bildschirmfoto 2018-05-15 um 11 57 33" src="https://user-images.githubusercontent.com/3305254/40050373-91fafff4-5837-11e8-9c19-08eaa5712473.png">
<img width="574" alt="bildschirmfoto 2018-05-15 um 11 57 35" src="https://user-images.githubusercontent.com/3305254/40050378-97e5e6fe-5837-11e8-90b1-53df7ada09dd.png">
<img width="1524" alt="bildschirmfoto 2018-05-15 um 11 58 04" src="https://user-images.githubusercontent.com/3305254/40050392-a1ad40d8-5837-11e8-82be-899ce2f463af.png">

Works absolutely fine on el capitan
<img width="698" alt="bildschirmfoto 2018-05-15 um 12 01 10" src="https://user-images.githubusercontent.com/3305254/40050435-c2dcab04-5837-11e8-80c7-10afd7db167c.png">

did you run the app with sudo ?

**Comment by alex-laties** [comment]
`airport-bssid` does definitely work on 10.13 High Sierra. The trick though is that the results from `option-click` on the WiFi icon are cached and incorrect after running `airport-bssid` and connecting to a new BSSID.

To check that you have connected to the desired BSSID, you can do the following:
```
~> cd /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/
~> ./airport -I | grep BSSID
```

**Comment by qpSHiNqp** [comment]
Same as #7. Let's discuss there.
